scale 1000 height
scale 1000 width
@startuml ClassDiagram

Vault -> Meta
Vault -> Database
class Vault {
    - meta : Meta
    - database : Database
    ---
    + Getter
    + Setter
}

Meta -> DateDataEntry
Meta -> HistoryEntry
class Meta {
    - version : String
    - datedata : List<DateDataEntry>
    - history : List<HistoryEntry>
    ---
    + Getter
    + Setter
}

class DateDataEntry {
    - id : int
    - timestamp : DateTime
    - changed : Bool
    ---
    + Getter
    + Setter
}

class HistoryEntry {
    - id : int
    - type : String
    - old : String
    - new : String
    ---
    + Getter
    + Setter
}

Database -> Group
Database -> Entry
class Database {
    - groups : List<Group>
    - entries : List<Entry>
    ---
    + Getter
    + Setter
}

Group -> Entry
class Group {
    - name : String
    - entries : List<Entry>
    - subGroups : List<Group>
    ---
    + Getter
    + Setter
}

class Entry {
    - title : String
    - username : String
    - password : String
    - email : String
    - link : String
    - notes : String
    - icon : String
    - tags : List<String>
    - logs : String
    ---
    + Getter
    + Setter
    + PasswordChecker
    + HaveIBeenPawned
}

class FileIO {

    ---

}

class Main {
    
    ---

}

class Cryption {

    ---

}

class ResponsiveLayoutManager {
    
    ---

}

class LoginPage  {
    
    ---

}

class VaultPage {
    
    ---

}



@enduml